/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qwirkle;

public class Domain {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Domain().getGreeting());
    }
}
