# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  TIMEOUT_SECONDS: 1

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - coverage

include:
  - template: Code-Quality.gitlab-ci.yml

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: 
    - gradle test jacocoTestReport
  artifacts:
    when: always
    reports:
      junit: 
        - domain/build/test-results/test/**/TEST-*.xml
        - api/build/test-results/test/**/TEST-*.xml
    paths:
      - domain/build/jacoco/jacocoTestReport.xml
      - domain/build/gl-code-quality-report.json
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

coverage:
  # Must be in a stage later than test's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or chose an existing stage like `deploy`.
  stage: coverage
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py domain/build/jacoco/jacocoTestReport.xml $CI_PROJECT_DIR/domain/src/main/java/ > domain/build/cobertura.xml
  needs: ["test"]
  artifacts:
    reports:
      cobertura: domain/build/cobertura.xml