/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qwirkle;

import org.junit.Test;
import static org.junit.Assert.*;

public class DomainTest {
    @Test public void appHasAGreeting() {
        Domain classUnderTest = new Domain();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
