/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qwirkle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import jakarta.servlet.http.*;
import jakarta.ws.rs.core.*;

public class DomainTest {
    @Test public void appHasAGreeting() {
        Domain classUnderTest = new Domain();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
