/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qwirkle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class apiTest {
    @Test public void appHasAGreeting() {
        api classUnderTest = new api();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
